apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app-label
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: node-app-label  
  template:
    metadata:
      labels:
        app: node-app-label  
    spec:
      containers:
      - name: node-app
        image: node-app 
        imagePullPolicy: Never
        ports:
        - containerPort: 3000   
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service 
spec:
  selector:
    app: node-app-label 
  type: LoadBalancer     
  ports:
  - protocol: TCP        
    port: 5000           
    targetPort: 3000    
    nodePort: 31110
