apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ip-default-service-app-deployment
  labels:
    app: cluster-ip-default-service-app
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: cluster-ip-default-service-app
  template:
    metadata:
      labels:
        app: cluster-ip-default-service-app
    spec:
      containers:
      - name: cluster-ip-default-service-app-container
        image: dockerrajani/node-21-express-app-macos-arm64:version1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-default-service
  labels:
    app: cluster-ip-default-service-app
spec:
  ports:
  - port: 8080
    targetPort: http-server
