apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-node-deployment
spec:
  selector:
    matchLabels:
      app: load-balancer-node-app
      paradigm: client-server
  replicas: 3
  template:
    metadata:
      labels:
        app: load-balancer-node-app
        paradigm: client-server
    spec:
      containers:
      - name: load-balancer-node-app-container
        image: "dockerrajani/node-21-express-app-macos-arm64:version1.0.0"
        env:
        - name: "PORT"
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-node-service
spec:
  clusterIP: 10.96.0.12
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30641
    port: 55555
    protocol: TCP
    targetPort: 8080
  selector:
    app: load-balancer-node-app
    paradigm: client-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 203.0.113.200
