apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  selector:
    matchLabels:
      app: expressjs
      framework: server
  replicas: 3
  template:
    metadata:
      labels:
        app: expressjs
        framework: server
    spec:
      containers:
      - name: expressjs-4-container
        image: "dockerrajani/node-21-express-app-macos-arm64:version1.0.0"
        env:
        - name: "PORT"
          value: "50001"
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: expressjs
    framework: server
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 50001
