apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-port-deployment
spec:
  selector:
    matchLabels:
      app: nodejs
      environment: runtime
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
        environment: runtime
    spec:
      containers:
      - name: nodejs-21-container
        image: "dockerrajani/node-21-express-app-macos-arm64:version1.0.0"
        env:
        - name: "PORT"
          value: "50000"
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: nodejs
    environment: runtime
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50000
