apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
      architecture: event-driven
  replicas: 3
  template:
    metadata:
      labels:
        app: node
        architecture: event-driven
    spec:
      containers:
      - name: node-21-container
        image: "dockerrajani/node-21-express-app-macos-arm64:version1.0.0"
        env:
        - name: "PORT"
          value: "50000"
