/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleJNI */

#ifndef _Included_SampleJNI
#define _Included_SampleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleJNI
 * Method:    hola
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleJNI_hola
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
