// Generated by jextract

package org.hello;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor helloworld$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle helloworld$MH = RuntimeHelper.downcallHandle(
        "helloworld",
        constants$0.helloworld$FUNC
    );
}


